### ISSUE TITLE
Feature Request: Propagating samples along wires automatically

### ISSUE THREAD

**Issue by emernic** [klavinslab/trident#32]
As a user, it would be convenient if I did not have to individually specify inputs and outputs that can be inferred from wires. For example, if I specify the output sample of a "PCR" operation and then create a wire connecting this output to the input of a "PCR Cleanup" operation, I would prefer to avoid explicitly specifying the input sample of this "PCR Cleanup" (because it can be inferred by the wire). This would make Trident scripts more compact and avoid accidental mismatches between connected operations.

**Comment by jvrana** [comment]
This has bee resolved in trident versions 0.1.5aX in the Planner instance model.
